#### Practical 5

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
'''Write a NumPy program to implement following operation
     1.to find the maximum and minimum value of a given flattened array

Name:JOSHI NIRALI KAILASH
Enrolment no.216270307067

'''
# Create a sample 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Flatten the 2D array to a 1D array
flattened_array = array_2d.flatten()

# Find the maximum and minimum values in the flattened array
max_value = np.max(flattened_array)
min_value = np.min(flattened_array)

# Print the results
print("Flattened Array:", flattened_array)
print("Maximum Value:", max_value)
print("Minimum Value:", min_value)

Flattened Array: [1 2 3 4 5 6 7 8 9]
Maximum Value: 9
Minimum Value: 1


In [3]:
 '''Write a NumPy program to implement following operation
     2.to compute the mean, standard deviation, and variance of a given 
         array along the second axis

Name:JOSHI NIRALI KAILASH
Enrolment no.216270307067

'''

a = np.arange(15).reshape(5,3)

print(a)
print("Mean of a along axis=1: ", np.mean(a, axis=1))

print("Standard Deviation along axis=1: \n", np.std(a, axis=1))

print("Variance along axis=1: \n", np.rint(np.var(a, axis=1)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Mean of a along axis=1:  [ 1.  4.  7. 10. 13.]
Standard Deviation along axis=1: 
 [0.81649658 0.81649658 0.81649658 0.81649658 0.81649658]
Variance along axis=1: 
 [1. 1. 1. 1. 1.]
