* **Practical 4**

#### 

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
# Write a NumPy program to implement following operation:
    # 1.to add, subtract, multiply, divide arguments element-wise.

# Name:Joshi Nirali Kailash
#Enrolment no.216270307067

import numpy as np

x=np.arange(10)
print("x =", x)
# using natve operators
print("\nx + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)    # floor division

# using builtin functions
print("\nUsing Ufuncs")
print("Addition:", np.add(x, 2))                    # Addition 
print("\nSubtraction:", np.subtract(x, 5))            # Subtraction 
print("\nMultiplication:", np.multiply(x, 3))          # Multiplication 
print("\nDivision:", np.divide(x, 2))              # Division 
print("\nnp.floor_divide(x, 2):", np.floor_divide(x, 2))   # Floor division

#using broadcasting
print("\nUsed broadcasting")
a = np.arange(3).reshape((3,1))
b = np.arange(1,4)
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)


x = [0 1 2 3 4 5 6 7 8 9]

x + 5 = [ 5  6  7  8  9 10 11 12 13 14]
x - 5 = [-5 -4 -3 -2 -1  0  1  2  3  4]
x * 2 = [ 0  2  4  6  8 10 12 14 16 18]
x / 2 = [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
x // 2 = [0 0 1 1 2 2 3 3 4 4]

Using Ufuncs
Addition: [ 2  3  4  5  6  7  8  9 10 11]

Subtraction: [-5 -4 -3 -2 -1  0  1  2  3  4]

Multiplication: [ 0  3  6  9 12 15 18 21 24 27]

Division: [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]

np.floor_divide(x, 2): [0 0 1 1 2 2 3 3 4 4]

Used broadcasting
Addition: [[1 2 3]
 [2 3 4]
 [3 4 5]]
Subtraction: [[-1 -2 -3]
 [ 0 -1 -2]
 [ 1  0 -1]]
Multiplication: [[0 0 0]
 [1 2 3]
 [2 4 6]]
Division: [[0.         0.         0.        ]
 [1.         0.5        0.33333333]
 [2.         1.         0.66666667]]


In [3]:
''' Write a NumPy program to implement following operation:
         2.to round elements of the array to the nearest integer

 Name:Joshi Nirali Kailash
Enrolment no.216270307067
'''
import numpy as np


np.round([.5, 1.5, 3.5, 7.5, 4.6, 5.4 ,4.6, 6.8]) 
np.around([.5, 1.5, 2.5, 3.5, 4.6, 5.4, 6.5, 7.8])            # equivalent to np.round()
print("Integer:",np.rint([.5, 1.5, 2.5, 3.5, 4.6, 5.4, 6.5, 7.8]))

Integer: [0. 2. 2. 4. 5. 5. 6. 8.]


In [4]:
'''Write a NumPy program to implement following operation:
        3.to calculate mean across dimension, in a 2D numpy array

 Name:Joshi Nirali Kailash
 Enrolment no.216270307067
'''
import numpy as np

arr=np.arange(10) #creating array

reshaped_arr=arr.reshape(2,5) #Reshaping 1D array
print(reshaped_arr)

print("\nMean of a: ", np.mean(reshaped_arr))
print("Mean of a along axis=0: ", np.mean(reshaped_arr, axis=0))
print("Mean of a along axis=1: ", np.mean(reshaped_arr, axis=1))

[[0 1 2 3 4]
 [5 6 7 8 9]]

Mean of a:  4.5
Mean of a along axis=0:  [2.5 3.5 4.5 5.5 6.5]
Mean of a along axis=1:  [2. 7.]


In [5]:
'''Write a NumPy program to implement following operation:
        4.to calculate the difference between neighboring elements, 
           element wise of a given array
I

 Name:Joshi Nirali Kailash
 Enrolment no.216270307067
'''
import numpy as np

arr1= np.array([[19, 7, 10, 12], [0, 12, 19, 8]])
print("Element Difference in 2D array:",np.diff(arr1))

Element Difference in 2D array: [[-12   3   2]
 [ 12   7 -11]]
