In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
#lab-2
    #Write a NumPy program to implement following operation
    # to split an array of 14 elements into 3 arrays, each with 2, 4, and 8 
    #elements in the original order
#Name:Nirali Joshi
#Enrollnment no:216270307067

import numpy as np

#original array
arr=np.array([15,14,13,12,10,9,8,7,6,5,4,3,2])
print("Numpy array",arr)

#splitted array
a1,a2,a3=np.split(arr,[2,6])
print("Splitted array:",a1,a2,a3)


Numpy array [15 14 13 12 10  9  8  7  6  5  4  3  2]
Splitted array: [15 14] [13 12 10  9] [8 7 6 5 4 3 2]


In [3]:
#lab-2
    #Write a NumPy program to implement following operation
    #to stack arrays horizontally (column wise)
#Name:Nirali Joshi
#Enrollnment no:216270307067

import numpy as np

#array using arange
arr = np.arange(25, dtype=np.float32).reshape((5,5))
print("Original Array  : \n", arr)

# Horizontally spliting array into 2 parts
left, right = np.hsplit(arr, [3])
print("\nLeft: \n", left)
print("\nRight: \n", right)


Original Array  : 
 [[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]

Left: 
 [[ 0.  1.  2.]
 [ 5.  6.  7.]
 [10. 11. 12.]
 [15. 16. 17.]
 [20. 21. 22.]]

Right: 
 [[ 3.  4.]
 [ 8.  9.]
 [13. 14.]
 [18. 19.]
 [23. 24.]]
